// src/Login.tsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';

const Login: React.FC = () => {
  const [showPassword, setShowPassword] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    navigate('/dashboard');
  };

  return (
    <>
      <main className="min-h-screen flex items-center justify-center px-gutter py-stack-lg relative overflow-hidden bg-gradient-to-br from-indigo-50 via-slate-50 to-purple-50">
        <div className="absolute top-0 -left-4 w-72 h-72 bg-primary/20 rounded-full mix-blend-multiply filter blur-3xl opacity-70 animate-blob"></div>
        <div className="absolute top-0 -right-4 w-72 h-72 bg-secondary/20 rounded-full mix-blend-multiply filter blur-3xl opacity-70 animate-blob animation-delay-2000"></div>
        <div className="absolute -bottom-8 left-20 w-72 h-72 bg-fuchsia-300/20 rounded-full mix-blend-multiply filter blur-3xl opacity-70 animate-blob animation-delay-4000"></div>
        
        <div className="relative w-full max-w-[480px] bg-white/80 backdrop-blur-xl border border-white/50 rounded-2xl overflow-hidden shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
          <div className="relative h-48 bg-primary-container overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-primary-container to-secondary-container opacity-90"></div>
            <img
              className="w-full h-full object-cover"
              alt="Abstract deep indigo and blue fluid gradient with subtle noise texture and professional geometric overlays"
              src="https://lh3.googleusercontent.com/aida-public/AB6AXuDr6mPBoZvHxcicedibSWbMv7AKsl_SUsGl0phm6T3IFttIe-HqfA1suGCKWUyNHoqXPfaDmyjpMNdBk2fNQuvbOgoAJVbseMC5fp6ROxsgdYScyDO_k0iNXvYo9zZo686Gd2hFUve0voNGzJSNZ2i_eN7qyHJnj9zQvf73otVYJsdds_7urmK9w2Wp8PhAawm9s7X2OouvNLEFobJkOgU0HHMt7FFGbvhw_KutWlwryo0LIQp2YunFyVOKx4mI16CmBTgByheBmg"
            />
            <div className="absolute inset-0 flex flex-col items-center justify-center text-on-primary">
              <span className="material-symbols-outlined text-4xl mb-2">hub</span>
              <h1 className="font-h1 text-h1 tracking-tight">ChatStream</h1>
              <p className="font-body-md text-body-md text-on-primary-container/80">Corporate Modern Workspace</p>
            </div>
          </div>
          <div className="p-8 md:p-10">
            <div className="mb-8">
              <h2 className="font-h2 text-h2 text-on-surface mb-1">Welcome Back</h2>
              <p className="font-body-md text-body-md text-on-surface-variant">Log in to access your dashboard.</p>
            </div>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <label className="font-label-sm text-label-sm text-on-surface-variant block" htmlFor="email">
                  Email Address
                </label>
                <div className="relative">
                  <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-[20px]">
                    mail
                  </span>
                  <input
                    className="w-full pl-10 pr-4 py-3 bg-white border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary-container/20 focus:border-primary-container transition-all"
                    id="email"
                    name="email"
                    placeholder="name@company.com"
                    required
                    type="email"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <label className="font-label-sm text-label-sm text-on-surface-variant block" htmlFor="password">
                    Password
                  </label>
                  <Link to="/forgot-password" className="font-meta text-meta text-primary-container hover:underline decoration-2 underline-offset-4 font-medium">
                    Forgot password?
                  </Link>
                </div>
                <div className="relative">
                  <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline text-[20px]">
                    lock
                  </span>
                  <input
                    className="w-full pl-10 pr-12 py-3 bg-white border border-outline-variant rounded-lg font-body-md text-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary-container/20 focus:border-primary-container transition-all"
                    id="password"
                    name="password"
                    placeholder="••••••••"
                    required
                    type={showPassword ? 'text' : 'password'}
                  />
                  <button
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-outline hover:text-on-surface-variant transition-colors"
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                  >
                    <span className="material-symbols-outlined text-[20px]">
                      {showPassword ? 'visibility_off' : 'visibility'}
                    </span>
                  </button>
                </div>
              </div>
              <button
                className="w-full py-3.5 bg-primary-container text-on-primary font-body-lg text-body-lg rounded-lg hover:opacity-90 active:scale-[0.98] transition-all duration-200 shadow-sm"
                type="submit"
              >
                Log In
              </button>
            </form>
            <div className="mt-8 pt-8 border-t border-outline-variant text-center">
              <p className="font-body-md text-body-md text-on-surface-variant">
                Don't have an account?{' '}
                <Link className="text-primary-container font-semibold hover:underline decoration-2 underline-offset-4" to="/register">
                  Register
                </Link>
              </p>
            </div>
          </div>
        </div>
      </main>

      <footer className="bg-slate-50 border-t border-slate-200 py-6 px-8 mt-auto">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="font-bold text-slate-900 font-manrope">ChatCorp</span>
          </div>
          <div className="flex gap-6">
            <a className="font-manrope text-xs text-slate-500 hover:text-indigo-700 transition-colors cursor-pointer" href="#">
              Privacy Policy
            </a>
            <a className="font-manrope text-xs text-slate-500 hover:text-indigo-700 transition-colors cursor-pointer" href="#">
              Terms of Service
            </a>
            <a className="font-manrope text-xs text-slate-500 hover:text-indigo-700 transition-colors cursor-pointer" href="#">
              Security Whitepaper
            </a>
          </div>
        </div>
      </footer>
    </>
  );
};

export default Login;

// chatty-app/src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { AuthLayoutComponent } from '../auth-layout/auth-layout.component';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, AuthLayoutComponent],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  email = '';
  password = '';
  rememberMe = true;
  submitting = false;
  error = '';

  constructor(private authService: AuthService, private router: Router) {}

  goRegister() {
    this.router.navigate(['/register']);
  }

  submit() {
    if (!this.email || !this.password) {
      return;
    }
    this.submitting = true;
    this.authService.login(this.email, this.password, this.rememberMe).subscribe({
      next: () => {
        this.submitting = false;
        this.router.navigate(['/chat']);
      },
      error: (err) => {
        this.submitting = false;
        this.error = err?.error?.title || 'Login failed';
      },
    });
  }
}

<app-auth-layout>
  <div class="w-full max-w-md space-y-8">
    <!-- Header -->
    <div>
      <div class="flex flex-wrap justify-between gap-3">
        <div class="flex w-full flex-col gap-1 text-center">
          <p class="text-[#111418] dark:text-white text-3xl font-black leading-tight tracking-[-0.033em]">Welcome Back
          </p>
          <p class="text-[#60758a] dark:text-gray-400 text-base font-normal leading-normal">Log in to continue to your
            account</p>
        </div>
      </div>
    </div>
    <!-- Segmented Buttons -->
    <div class="flex py-3">
      <div
        class="flex h-12 flex-1 items-center justify-center rounded-lg bg-background-light dark:bg-background-dark p-1">
        <label
          class="flex cursor-pointer h-full grow items-center justify-center overflow-hidden rounded-lg px-2 has-[:checked]:bg-white has-[:checked]:shadow-sm has-[:checked]:text-primary dark:has-[:checked]:bg-primary/10 dark:has-[:checked]:text-primary text-[#60758a] dark:text-gray-400 text-sm font-medium leading-normal transition-all duration-200">
          <span>Login</span>
          <input class="invisible w-0" name="auth-toggle" type="radio" value="Login" checked />
        </label>
        <label
          class="flex cursor-pointer h-full grow items-center justify-center overflow-hidden rounded-lg px-2 has-[:checked]:bg-white has-[:checked]:shadow-sm has-[:checked]:text-primary dark:has-[:checked]:bg-primary/10 dark:has-[:checked]:text-primary text-[#60758a] dark:text-gray-400 text-sm font-medium leading-normal transition-all duration-200">
          <span class="whitespace-nowrap">Sign Up</span>
          <input class="invisible w-0" name="auth-toggle" type="radio" value="Sign Up" (change)="goRegister()" />
        </label>
      </div>
    </div>
    <!-- Form -->
    <form class="space-y-6" (ngSubmit)="submit()">
      <!-- Email Field -->
      <div class="flex flex-wrap items-end gap-4">
        <label class="flex flex-col min-w-40 flex-1">
          <p class="text-[#111418] dark:text-gray-300 text-sm font-medium leading-normal pb-2">Email Address</p>
          <input
            class="form-input flex w-full min-w-0 flex-1 rounded-lg text-[#111418] dark:text-white focus:outline-0 focus:ring-2 focus:ring-primary/50 border border-[#dbe0e6] dark:border-gray-700 bg-white dark:bg-background-dark h-12 placeholder:text-[#60758a] p-3 text-base font-normal leading-normal"
            placeholder="Enter your email" type="email" name="email" [(ngModel)]="email" required />
        </label>
      </div>
      <!-- Password Field -->
      <div class="flex flex-wrap items-end gap-4">
        <label class="flex flex-col min-w-40 flex-1">
          <div class="flex justify-between items-center pb-2">
            <p class="text-[#111418] dark:text-gray-300 text-sm font-medium leading-normal">Password</p>
            <a class="text-sm font-medium text-primary hover:underline" href="#">Forgot Password?</a>
          </div>
          <div class="relative w-full">
            <input
              class="form-input flex w-full min-w-0 flex-1 rounded-lg text-[#111418] dark:text-white focus:outline-0 focus:ring-2 focus:ring-primary/50 border border-[#dbe0e6] dark:border-gray-700 bg-white dark:bg-background-dark h-12 placeholder:text-[#60758a] p-3 pr-10 text-base font-normal leading-normal"
              placeholder="Enter your password" type="password" name="password" [(ngModel)]="password" required />
            <button type="button"
              class="absolute inset-y-0 right-0 flex items-center pr-3 text-[#60758a] dark:text-gray-400">
              <span class="material-symbols-outlined text-xl">visibility_off</span>
            </button>
          </div>
        </label>
      </div>
      <div class="pt-1">
        <label
          class="flex items-center gap-4 rounded-2xl border border-[#dbe0e6] dark:border-gray-700 bg-white/90 dark:bg-background-dark px-4 py-3 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"
        >
          <div class="flex flex-col leading-tight">
            <span class="text-sm font-semibold text-[#111418] dark:text-gray-100">Remember me</span>
            <span class="text-xs text-[#60758a] dark:text-gray-400">Stay signed in on this device</span>
          </div>
          <span class="ml-auto relative inline-flex h-7 w-12 items-center justify-center">
            <input
              type="checkbox"
              name="rememberMe"
              [(ngModel)]="rememberMe"
              class="peer sr-only"
            />
            <span
              class="h-7 w-12 rounded-full border border-[#cfd5df] bg-[radial-gradient(circle_at_30%_30%,#dfe5f0_0,#c6cbd7_55%,#b9beca_100%)] dark:bg-gray-700 dark:border-gray-600 transition-all duration-200 shadow-inner peer-checked:border-transparent peer-checked:bg-gradient-to-r peer-checked:from-[#2563eb] peer-checked:to-[#4f8bff] peer-checked:shadow-[0_8px_18px_rgba(64,80,255,0.35)]"
            ></span>
            <span
              class="absolute left-1 h-5 w-5 rounded-full bg-white shadow-[0_2px_6px_rgba(0,0,0,0.12)] transition-transform duration-200 peer-checked:translate-x-5 peer-checked:shadow-[0_6px_14px_rgba(0,0,0,0.16)]"
            ></span>
          </span>
        </label>
      </div>
      <!-- CTA Button -->
      <div class="py-2">
        <button type="submit" [disabled]="submitting"
          class="flex h-12 w-full items-center justify-center rounded-lg bg-primary px-6 text-base font-semibold text-white shadow-sm hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary/50 focus:ring-offset-2 dark:ring-offset-background-dark transition-colors duration-200">
          {{ submitting ? 'Signing in...' : 'Log In' }}
        </button>
        <p class="text-sm text-red-600 mt-2" *ngIf="error">{{ error }}</p>
      </div>
    </form>
  </div>
</app-auth-layout>
